In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('../main/log/random_study__20250812.csv', header = None, names = ['Seed', 'Mutation', 
                                                                           'T1 nodes', 'T1 nodes as', 'T1 k_complexity', 'T1 sb_complexity',
                                                                           'T1 sharpness', 
                                                                           'T2 nodes', 'T2 nodes as', 'T2 k_complexity', 'T2 sb_complexity', 
                                                                           'T2 sharpness',
                                                                           'Mut nodes', 'Mut nodes as', 'Mut k_complexity', 'Mut sb_complexity',
                                                                           'Mut sharpness'])

In [3]:
data.head(12)

,Seed,Mutation,T1 nodes,T1 nodes as,T1 k_complexity,T1 sb_complexity,T1 sharpness,T2 nodes,T2 nodes as,T2 k_complexity,T2 sb_complexity,T2 sharpness,Mut nodes,Mut nodes as,Mut k_complexity,Mut sb_complexity,Mut sharpness
0,0,S1,3,3,24,224878.946156,0.999371,NaN,NaN,NaN,NaN,NaN,15,38,98,9206.240520,0.999585
1,0,ABS,3,3,24,224878.946156,0.999371,NaN,NaN,NaN,NaN,NaN,12,15,86,5239.638198,0.994488
2,0,S2,3,3,24,224878.946156,0.999371,3.0,3.0,26.0,27488.854319,0.994430,21,21,104,8367.887862,0.993668
3,1,S1,5,6,44,49690.173576,0.989652,NaN,NaN,NaN,NaN,NaN,17,14,107,846.500837,0.938433
4,1,ABS,5,6,44,49690.173576,0.989652,NaN,NaN,NaN,NaN,NaN,14,21,96,22.978743,0.964210
5,1,S2,5,6,44,49690.173576,0.989652,3.0,3.0,27.0,42636.166828,0.948351,23,23,109,19.935102,0.992866
6,2,S1,7,11,44,112445.601148,0.993686,NaN,NaN,NaN,NaN,NaN,19,62,109,10561.782116,0.999789
7,2,ABS,7,11,44,112445.601148,0.993686,NaN,NaN,NaN,NaN,NaN,16,14,97,4396.606188,0.832644
8,2,S2,7,11,44,112445.601148,0.993686,3.0,3.0,23.0,51496.201346,0.999608,25,26,113,19625.817088,0.998075
9,3,S1,3,3,28,268813.299342,0.992395,NaN,NaN,NaN,NaN,NaN,15,30,97,16480.755700,0.997220
10,3,ABS,3,3,28,268813.299342,0.992395,NaN,NaN,NaN,NaN,NaN,12,15,88,9967.590878,0.980297
11,3,S2,3,3,28,268813.299342,0.992395,3.0,3.0,24.0,69170.862590,0.999546,21,21,105,7504.941463,0.989605

In [4]:
data['T1 nodes as'] = data.apply(lambda x: x['T1 nodes as'] if x['T1 nodes'] >= x['T1 nodes as'] else x['T1 nodes'], axis = 1)
data['T2 nodes as'] = data.apply(lambda x: x['T2 nodes as'] if x['T2 nodes'] >= x['T2 nodes as'] else x['T2 nodes'], axis = 1)
data['Mut nodes as'] = data.apply(lambda x: x['Mut nodes as'] if x['Mut nodes'] >= x['Mut nodes as'] else x['Mut nodes'], axis = 1)

In [5]:
data.head(12)

,Seed,Mutation,T1 nodes,T1 nodes as,T1 k_complexity,T1 sb_complexity,T1 sharpness,T2 nodes,T2 nodes as,T2 k_complexity,T2 sb_complexity,T2 sharpness,Mut nodes,Mut nodes as,Mut k_complexity,Mut sb_complexity,Mut sharpness
0,0,S1,3,3,24,224878.946156,0.999371,NaN,NaN,NaN,NaN,NaN,15,15,98,9206.240520,0.999585
1,0,ABS,3,3,24,224878.946156,0.999371,NaN,NaN,NaN,NaN,NaN,12,12,86,5239.638198,0.994488
2,0,S2,3,3,24,224878.946156,0.999371,3.0,3.0,26.0,27488.854319,0.994430,21,21,104,8367.887862,0.993668
3,1,S1,5,5,44,49690.173576,0.989652,NaN,NaN,NaN,NaN,NaN,17,14,107,846.500837,0.938433
4,1,ABS,5,5,44,49690.173576,0.989652,NaN,NaN,NaN,NaN,NaN,14,14,96,22.978743,0.964210
5,1,S2,5,5,44,49690.173576,0.989652,3.0,3.0,27.0,42636.166828,0.948351,23,23,109,19.935102,0.992866
6,2,S1,7,7,44,112445.601148,0.993686,NaN,NaN,NaN,NaN,NaN,19,19,109,10561.782116,0.999789
7,2,ABS,7,7,44,112445.601148,0.993686,NaN,NaN,NaN,NaN,NaN,16,14,97,4396.606188,0.832644
8,2,S2,7,7,44,112445.601148,0.993686,3.0,3.0,23.0,51496.201346,0.999608,25,25,113,19625.817088,0.998075
9,3,S1,3,3,28,268813.299342,0.992395,NaN,NaN,NaN,NaN,NaN,15,15,97,16480.755700,0.997220
10,3,ABS,3,3,28,268813.299342,0.992395,NaN,NaN,NaN,NaN,NaN,12,12,88,9967.590878,0.980297
11,3,S2,3,3,28,268813.299342,0.992395,3.0,3.0,24.0,69170.862590,0.999546,21,21,105,7504.941463,0.989605

In [8]:
data[['Mutation', 'Mut nodes', 'Mut nodes as', 'Mut k_complexity', 'Mut sb_complexity', 'Mut sharpness']].groupby('Mutation').median().T

Mutation                   ABS           S1           S2
Mut nodes            12.000000    15.000000    23.000000
Mut nodes as         12.000000    15.000000    22.000000
Mut k_complexity     88.000000    99.000000   106.000000
Mut sb_complexity  3678.548985  6553.464077  4870.974802
Mut sharpness         0.959478     0.994650     0.992542

In [12]:
data[['Mut nodes', 'Mut nodes as', 'Mut k_complexity', 'Mut sb_complexity', 'Mut sharpness']].corr()

,Mut nodes,Mut nodes as,Mut k_complexity,Mut sb_complexity,Mut sharpness
Mut nodes,1.000000,0.946193,0.918872,-0.022657,-0.002685
Mut nodes as,0.946193,1.000000,0.878202,-0.012894,-0.002923
Mut k_complexity,0.918872,0.878202,1.000000,-0.011681,-0.026342
Mut sb_complexity,-0.022657,-0.012894,-0.011681,1.000000,0.009852
Mut sharpness,-0.002685,-0.002923,-0.026342,0.009852,1.000000